// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBfgiuHFJU2w7DZIMRrr0v12crtYEcNtK4',
    appId: '1:1033003422873:web:4df614506c689bf8f71408',
    messagingSenderId: '1033003422873',
    projectId: 'low-office',
    authDomain: 'low-office.firebaseapp.com',
    storageBucket: 'low-office.appspot.com',
    measurementId: 'G-44HDZ972J2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-sqdsbYLxbz3dtpkP7IDEUnPngX5pOk4',
    appId: '1:1033003422873:android:908dea2dc7da98caf71408',
    messagingSenderId: '1033003422873',
    projectId: 'low-office',
    storageBucket: 'low-office.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCt6q3kZednbkkx3SpLJhPIZv03E7S6eec',
    appId: '1:1033003422873:ios:85d5a3319c29eb0df71408',
    messagingSenderId: '1033003422873',
    projectId: 'low-office',
    storageBucket: 'low-office.appspot.com',
    iosBundleId: 'com.example.lowOffice',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCt6q3kZednbkkx3SpLJhPIZv03E7S6eec',
    appId: '1:1033003422873:ios:85d5a3319c29eb0df71408',
    messagingSenderId: '1033003422873',
    projectId: 'low-office',
    storageBucket: 'low-office.appspot.com',
    iosBundleId: 'com.example.lowOffice',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBfgiuHFJU2w7DZIMRrr0v12crtYEcNtK4',
    appId: '1:1033003422873:web:0f2223dc83a27529f71408',
    messagingSenderId: '1033003422873',
    projectId: 'low-office',
    authDomain: 'low-office.firebaseapp.com',
    storageBucket: 'low-office.appspot.com',
    measurementId: 'G-9LRHRD05C2',
  );

}